# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest


stages:
  - stage: Build
    jobs:
      - job: Build_react
        displayName: React Build
        steps:
        - task: NodeTool@0
          inputs:
           versionSpec: '10.x'

        - script: |
               npm install
               npm run build
            
        - task: CopyFiles@2
          inputs:
            SourceFolder: '$(System.DefaultWorkingDirectory)'
            TargetFolder: '$(Build.ArtifactStagingDirectory)'
          
        - task: ArchiveFiles@2
          inputs:
            rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
            includeRootFolder: true
            archiveType: 'zip'
            archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
            replaceExistingArchive: true
          displayName: Archiving the content
          
        - task: PublishBuildArtifacts@1
          inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'ReactArtifact'
              publishLocation: 'Container'

