# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest


stages:
  - stage: Build
    jobs:
      - job: Build_react
        displayName: React Build
        steps:
        - task: NodeTool@0
          inputs:
           versionSpec: '10.x'

        - script: |
               npm install
               npm run build
            
        - task: CopyFiles@2
          inputs:
            SourceFolder: '$(System.DefaultWorkingDirectory)'
            Contents: |
                **\*.js
                package.json
            TargetFolder: '$(Build.ArtifactStagingDirectory)'

        - task: ArchiveFiles@2
          inputs:
            rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
            includeRootFolder: true
            archiveType: 'zip'
            archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
            replaceExistingArchive: true
          displayName: Archiving the content
          
        - task: PublishPipelineArtifact@1
          inputs:
              targetPath: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
              artifact: 'ReactArtifact'
              publishLocation: 'pipeline'
              

